POST http://localhost:5005/task-manager/auth/register
Content-Type: application/json

{
    "first_name": "Test",
    "last_name": "Test",
    "email": "example1@example.com",
    "password": "123456789"
}

